#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: "Chris Ward" <cward@redhat.com>

# PY3 COMPAT
from __future__ import unicode_literals, absolute_import

"""
Git pre-commit hooks for stats-report.
"""

import argparse
import logging
import sys

from members.utils import logr, run

# Turn on DEBUG so we can get a full log on each commit
logr.setLevel(logging.DEBUG)


def run_tests():
    '''
    Run all the available tests.
    '''
    logr.warn(" RUNNING TESTS <<")
    # Try to run make build
    cmd = "py.test tests"
    output, errors = run(cmd)
    return 0


def make_sdist():
    '''
    Make sure we haven't broken the rpm source builds
    '''
    logr.warn(" RUNNING SDIST <<")
    # Try to build a python pip installable package
    cmd = 'python setup.py sdist'
    output, errors = run(cmd)
    return 0


def flake8():
    '''
    `get_git_param` will retrieve configuration from your local git config and
    then fall back to using the environment variables that the hook has always
    supported.

    For example, to set the complexity, you'll need to do:
        git config flake8.complexity 10
    '''
    logr.warn(" RUNNING FLAKE8 <<")
    ecode = 0
    try:
        from flake8.hooks import git_hook, get_git_param
    except ImportError:
        logr.warn(' .. Skipping flake8. `pip install flake8` required.')
        ecode = 1
    else:
        COMPLEXITY = get_git_param('FLAKE8_COMPLEXITY', 10)
        STRICT = get_git_param('FLAKE8_STRICT', False)
        IGNORE = get_git_param('FLAKE8_IGNORE', None)
        LAZY = get_git_param('FLAKE8_LAZY', False)
        ecode = git_hook(complexity=COMPLEXITY, strict=STRICT,
                        ignore=IGNORE, lazy=LAZY)
    return ecode


def main():
    """ Main function handling configuration files etc """
    parser = argparse.ArgumentParser(
        description='Git python commit hooks')
    parser.add_argument(
        '--make-rpm', action='store_const', const=True, default=True,
        help='Build RPMs from source')
    parser.add_argument(
        '--run-tests', action='store_const', const=True, default=True,
        help='Run all available tests')
    parser.add_argument(
        '--stash-first', action='store_const', const=True, default=False,
        help='Run all available tests')
    args = parser.parse_args()

    # make sure we're working with only the staged content!
    if args.stash_first:
        run('git stash -q --keep-index')

    try:
        results = []
        if args.run_tests:
            results.append({'run_tests': run_tests()})
    finally:
        # make sure we return things back to how they started
        if args.stash_first:
            run('git stash pop -q')

    print results
    ecode = 0 if all(results) else 1

    logr.debug(' EXIT: {} <<'.format(ecode))
    sys.exit(ecode)

if __name__ == '__main__':
    main()
